Added json.md - Serialization part
opensearch-project/opensearch-java pull request #1083
Opened 2024-07-15 17:09 UTC by Jai2305

### Description
* Adding documentation  json.md in guides folder for Json serialization with openSearch java Client.
* Adding code samples to guide users to use the `toJsonString `method added here and manual serialization with serialize method in `JsonpSerializable`

### Issues Resolved
Documentation for Json serialization with code samples

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-07-15 17:11 UTC, Jai2305 commented
In response to @dblock's ask for documentation I have added json.md in guides folder with code samples demonstrating the usage of toJsonString.

2024-07-15 17:17 UTC, reta commented on guides/json.md
> +This method utilizes the default mapper and generator from the JsonpUtils class within the package to streamline the serialization process.
```suggestion
This implementation uses `jakarta.json.spi.JsonProvider` SPI to discover the available JSON provider instance from the classpath and to create a new mapper. The `JsonpUtils` utility class streamlines this serialization process.
```

2024-07-15 18:12 UTC, reta submitted a review, later dismissed

2024-07-15 19:40 UTC, dblock requested changes
Looks great, I have a bunch of nits, please.

Also link the new doc from USER_GUIDE

2024-07-15 19:40 UTC, dblock commented on CHANGELOG.md
> +- Add a new file json.md in guides and SerializationBasics in samples/json ([#1083](https://github.com/opensearch-project/opensearch-java/pull/1083))
Nit: I would collapse the two changelog items and just say that we added request serialization to JSON.

2024-07-15 19:40 UTC, dblock commented on guides/json.md
> +    - [Using toJsonString method](#using-tojsonstring-method)
Using `toJsonString` (quote, remove method)

2024-07-15 19:40 UTC, dblock commented on guides/json.md
> +    - [Manual serialization](#manually-serialize-by-providing-mapper-and-generator)
Capitalize sections consistently, so "Manual Serialization"

2024-07-15 19:40 UTC, dblock commented on guides/json.md
> +OpenSearch Java client seamlessly integrate with JSON providing serialization and deserialization capability.
integrates

, providing

2024-07-15 19:40 UTC, dblock commented on guides/json.md
> +public static void main(final String[] args) {
remove main, keep the body of it

2024-07-15 19:40 UTC, dblock commented on guides/json.md
> +    - [Using toJsonString method](#using-tojsonstring-method)
Update TOC to match body.

2024-07-15 19:40 UTC, dblock commented on guides/json.md
> +
Remove extra lines.

2024-07-16 15:43 UTC, dblock approved these changes

2024-07-16 15:43 UTC, merged

2024-07-16 15:44 UTC, dblock commented
Merged, thank you!