Removed null constraints on NodeInfo fields that are returned null from Amazon OpenSearch Service
opensearch-project/opensearch-java pull request #1131
Opened 2024-08-07 15:06 UTC by dancristiancecoi

### Description
This change removes null constraints on NodeInfo.Host, NodeInfo.Ip, NodeInfo.TransportAddress that are returned null from Amazon OpenSearch Service when performing a NodeInfoRequest

### Issues Resolved
#1129 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-08-07 15:12 UTC, dancristiancecoi commented
Have some questions about the Changelog. I want this backported to 2.x if approved, do I add an entry to the 2.x section as well or just to the 3.x?

2024-08-07 19:14 UTC, dblock commented
> Have some questions about the Changelog. I want this backported to 2.x if approved, do I add an entry to the 2.x section as well or just to the 3.x one?

2.x I believe

2024-08-07 22:18 UTC, Xtansia commented
> Have some questions about the Changelog. I want this backported to 2.x if approved, do I add an entry to the 2.x section as well or just to the 3.x one?

 Entries should only go under one section or the other not both, so for your case It would go under only the `Unreleased 2.x` section

2024-08-07 22:23 UTC, Xtansia requested changes

2024-08-07 22:23 UTC, Xtansia commented on java-client/src/main/java/org/opensearch/client/opensearch/nodes/info/NodeInfo.java
> +    @Nullable
The relevant getters below should also get `@Nullable` annotations

2024-08-07 22:23 UTC, Xtansia commented on java-client/src/main/java/org/opensearch/client/opensearch/nodes/info/NodeInfo.java
> +        public final Builder transportAddress(@Nullable  String value) {
Please fix the double space here, or just run `./gradlew spotlessApply`
```suggestion
        public final Builder transportAddress(@Nullable String value) {
```

2024-08-08 10:49 UTC, dancristiancecoi commented
Thanks guys!

2024-08-08 12:24 UTC, dancristiancecoi commented
Ugh, I messed up the rebase trying to solve the conflicts. I will close this PR and open a new one as it will be quicker this way. Sorry :D

2024-08-08 12:24 UTC, closed without merging