Add changelog and changelog verifier
opensearch-project/opensearch-java pull request #242
Opened 2022-10-14 17:09 UTC by harshavamsi

Signed-off-by: Harsha Vamsi Kalluri <harshavamsi096@gmail.com>

### Description
Introduces changelog and changelog verifier

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has comments added
  - [X] New functionality is added to `docs` folder
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](https://github.com/opensearch-project/opensearch-java/blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/opensearch-java/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-10-14 17:28 UTC, saratvemulapalli approved these changes

2022-10-14 19:19 UTC, dblock requested changes
Some more nits pls.

2022-10-14 19:19 UTC, dblock commented on CONTRIBUTING.md
> +### Adding changes
Should be "Adding Changes" to be consistent (capital C)

2022-10-14 19:19 UTC, dblock commented on CONTRIBUTING.md
> +OpenSearch-Java maintains a version specific changelog by enforcing a change to the ongoing [CHANGELOG](CHANGELOG.md) file adhering to the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) for
The project is Opensearch-java (capital O because start of sentence).

Version-specific I think has a `-`.

2022-10-18 17:02 UTC, harshavamsi commented
@dblock updated with asks. I removed the PR template after our discussion [here](https://github.com/opensearch-project/opensearch-go/pull/172#discussion_r996064830)

2022-10-18 18:36 UTC, VachaShah submitted a review, later dismissed

2022-10-19 13:18 UTC, dblock approved these changes

2022-10-19 17:31 UTC, VachaShah approved these changes

2022-10-19 17:31 UTC, merged