Include aggregations and suggest in SearchTemplateResponse
opensearch-project/opensearch-java pull request #462
Opened 2023-04-25 11:58 UTC by eNorby1

### Description
Added support for aggregations and suggest in SearchTemplateResponse

### Issues Resolved
Resolves [#456](https://github.com/opensearch-project/opensearch-java/issues/456)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-04-25 16:05 UTC, dblock requested changes
This is great! Just needs tests, please.

2023-04-28 08:40 UTC, eNorby1 commented
Hi @dblock and others, can you please check? :)

2023-04-28 16:55 UTC, dblock approved these changes
This looks great! Super idea. I don't see any downsides, @reta?

2023-05-01 13:49 UTC, reta commented
> This looks great! Super idea. I don't see any downsides, @reta?

@eNorby1 I really like the direction you ended up at, I would suggest minor design change: introduce intermediary `SearchResult<TDocument>` class so both `SearchResponse` and `SearchTemplateResponse` could inherit from it.

Why I am suggestion that instead of subclassing `SearchResponse` directly: besides the fact that  `SearchTemplateResponse`  hides some static fields of the `SearchResponse` (not a big deal but could be surprising), the change gives an impression that`SearchTemplateResponse` is not really needed and  `SearchResponse` could be used instead (with intermediary class we basically inherit implementation only).

2023-05-01 15:55 UTC, eNorby1 commented
@reta makes sense. I'll have a look, thanks

2023-05-02 08:34 UTC, eNorby1 commented
Hi @reta I did the change you suggested, can you please check?

2023-05-02 12:40 UTC, reta commented on java-client/src/main/java/org/opensearch/client/opensearch/core/search/SearchResult.java
> +/*
Super nit, but we could only keep this part of the header, this is new file and is not inherited from Elasticsearch

2023-05-02 12:42 UTC, reta commented
> Hi @reta I did the change you suggested, can you please check?

Thanks a lot @eNorby1 , it looks great, nit comment regarding the copyright header, LGTM otherwise!

2023-05-02 12:59 UTC, reta commented on java-client/src/main/java/org/opensearch/client/opensearch/core/search/SearchResult.java
> +public abstract class SearchResult<TDocument> implements JsonpSerializable {
Fair enough, thank you

2023-05-02 13:49 UTC, reta approved these changes

2023-05-02 17:02 UTC, VachaShah approved these changes

2023-05-02 17:07 UTC, merged