Bumps 'jackson' from 4.14.2 to 4.15.2
opensearch-project/opensearch-java pull request #537
Opened 2023-06-22 17:03 UTC by reta

### Description
Bumps 'jackson' from 4.14.2 to 4.15.2

### Issues Resolved
N/A

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-06-22 21:51 UTC, Xtansia requested changes

2023-06-22 21:51 UTC, Xtansia commented on CHANGELOG.md
> +- Bumps `jackson` from 4.14.2 to 4.15.2 ((#537)[https://github.com/opensearch-project/opensearch-java/pull/537])
Typo here, should be `2.x.x` (same in PR title):
```suggestion
- Bumps `jackson` from 2.14.2 to 2.15.2 ((#537)[https://github.com/opensearch-project/opensearch-java/pull/537])
```

2023-06-23 13:04 UTC, szczepanczykd approved these changes

2023-06-26 22:54 UTC, dblock approved these changes

2023-06-26 22:54 UTC, merged