Moving "software.amazon.awssdk" dependencies to the compileOnly scope.
opensearch-project/opensearch-java pull request #628
Opened 2023-09-20 08:32 UTC by dkaukov

### Description
Current build configuration leaking "software.amazon.awssdk" dependencies to the final POM:
```
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>sdk-core</artifactId>
      <version>[2.15,3.0)</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>auth</artifactId>
      <version>[2.15,3.0)</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
```
Which breaks some maven plugins (notable https://github.com/basepom/dependency-versions-check-maven-plugin) which tries to download all possible versions of the SDK in range.

### Issues Resolved
By changing scope to the `compileOnly`,  we completely  removing this dependencies from final POM

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-09-20 08:56 UTC, dblock commented
Thanks! could you please check DCO (`git commit -s --amend`) and update the PR?

2023-09-20 14:02 UTC, reta requested changes

2023-09-20 14:02 UTC, reta commented on java-client/build.gradle.kts
> +    compileOnly("software.amazon.awssdk","sdk-core","[2.15,3.0)")
```suggestion
    "awsSdk2SupportCompileOnly"("software.amazon.awssdk","sdk-core","[2.15,3.0)")
    "awsSdk2SupportCompileOnly"("software.amazon.awssdk","auth","[2.15,3.0)")
```

2023-09-20 22:28 UTC, dkaukov commented on java-client/build.gradle.kts
> +    compileOnly("software.amazon.awssdk","sdk-core","[2.15,3.0)")
Done

2023-09-20 23:55 UTC, reta approved these changes

2023-09-20 23:56 UTC, reta commented
@dkaukov could you please add a changelog entry, thank you

2023-09-22 11:44 UTC, reta approved these changes

2023-09-22 17:14 UTC, VachaShah approved these changes
Thank you @dkaukov!

2023-09-22 17:14 UTC, merged

2023-09-22 18:15 UTC, VachaShah commented
Backport in #634