Serialize requests to json
opensearch-project/opensearch-java pull request #694
Opened 2023-10-29 20:57 UTC by Tamir-Schwarz

link to issue
https://github.com/opensearch-project/opensearch-java/issues/588

actually used the code of `Daniel Doubrovkine (dB.)` - thank you very much!

original example
https://github.com/dblock/opensearch-java-client-demo/blob/to-json/src/main/java/Example.java#L34

=========
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

2023-10-30 15:28 UTC, dblock requested changes
I think with some documentation in USER_GUIDE or related this could be good enough.

2023-10-30 15:28 UTC, dblock commented on java-client/src/test/java/org/opensearch/client/opensearch/json/JsonDataTest.java
> +        System.out.println(json);
Get rid of print outs.

2023-10-30 18:39 UTC, VachaShah commented
> I think with some documentation in USER_GUIDE or related this could be good enough.

+1. Some documentation on how to use `toJson()` for a class would be great!

2023-12-04 15:11 UTC, dblock commented
@Tamir-Schwarz Want to finish this?

2024-07-02 12:45 UTC, felipetoffolo-toast commented
I don't think that this work. I can't find toJson function

2024-07-02 16:55 UTC, Jai2305 commented
Hi @Tamir-Schwarz and @dblock , first of thanks for the contribution, all services of my organization are migrating from the High Level Rest Client to Java Client and very much like these kind of enhancements to be implemented, as they provide a clean code convenience to new clients.
Although I have some suggestions and I would like your opinion on them - 
* Can we not implement this method in JsonpSerializable interface as a default method, I think it will be a better design as it will ensure that only classes implementing the interface are allowed to utilize the default method, you could internally call serialize method of the interface, this will avoid implementation and call to a utils class.
* Also you can try implementing `JsonGenerator generator = mapper.jsonProvider().createGenerator(stringWriter);` with try with resource block to ensure that  the generator is closed automatically even if an exception occurs.
* Finally please include test cases for classes which are implementing JsonpSerializable indirectly, just to ensure the robustness of code , for eg. IndexResponse extends WriteResponseBase implements JsonpSerializable .

2024-07-02 17:33 UTC, dblock commented
@Jai2305 These look very reasonable. Want to open another PR with your suggestions?

2024-07-02 18:01 UTC, Jai2305 commented
@dblock thanks for a quick response, I am on it.

2024-11-21 23:27 UTC, Xtansia commented
A version of this utility was added via #588, documented here: https://github.com/opensearch-project/opensearch-java/blob/main/guides/json.md#using-tojsonstring

2024-11-21 23:27 UTC, closed without merging