fix(parent/agg): deserialize parent aggregation
opensearch-project/opensearch-java pull request #706
Opened 2023-11-02 17:15 UTC by romansmirnov

### Description
When performing a parent aggregation, the deserialization of the search response failed because the parent aggregate deserializer was not registered.

This PR introduces a `ParentAggregate` and provides a `_DESERIALIZER` that is being used to deserialize the search response containing the results of the parent aggregation.

If possible could you please backport this bug fix up to version 2.5 of the java client.

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-11-03 15:03 UTC, dblock requested changes
Thanks for the fix! Add to CHANGELOG and write a test, please. Also a good opportunity to write a sample that exercises this feature.

2023-11-13 08:01 UTC, romansmirnov commented
@dblock, thanks for looking into it. I will try to provide some test cases this week.

2024-06-21 18:41 UTC, romansmirnov commented
@dblock, thanks for your patience 😄 I added a note to the Changelog and two test cases to test the deserialization and the builder. Hopefully, the changes can now be merged. If so, could this fix be backported to 2.x as well?

2024-06-21 20:42 UTC, dblock approved these changes

2024-06-21 20:42 UTC, merged

2024-06-21 20:44 UTC, dblock commented
Looks great, merged. 

Can you do a manual backport to 2.x please? Looks like the automated one failed.

Also note that we've been working on https://github.com/opensearch-project/opensearch-api-specification and a code generator to replace rolling these out manually. If you have time, check out that repo and make sure this part of the spec is properly represented and add tests.