Fix missing properties on UpdateOperation
opensearch-project/opensearch-java pull request #748
Opened 2023-11-28 07:38 UTC by fs-chris

### Description
Adds missing properties `scriptedUpder` and `detectNoop` to `UpdateOperation`

### Issues Resolved
Fixes #744 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-11-28 17:42 UTC, dblock requested changes
Thanks! This will need tests to get merged, please? Also amend your commits with `-s` for DCO to pass.

2023-11-29 10:51 UTC, fs-chris commented
The DCO thing is really a pain.
I hope that all requirements are met now.
If not, feel free to discard this PR and manually merge the changes into an own one.

2023-11-29 13:33 UTC, reta approved these changes

2023-11-29 21:35 UTC, dblock commented
> The DCO thing is really a pain.

Yeah you get used to it :) It's really a small price to pay to make non-Engineers happy.

2023-11-29 21:36 UTC, dblock approved these changes
Thanks for hanging out with us @fs-chris!

2023-11-29 21:36 UTC, merged

2023-11-29 21:36 UTC, dblock commented
Oh crap I hit merge but just realized this PR was made into the 2.8.1 branch :( That wasn't supposed to happen. I'll revert.

2023-11-29 21:49 UTC, dblock commented
@fs-chris You need to make this PR into `main` and then we can backport it onto 2.x for the next 2.x release.

2023-11-30 07:17 UTC, fs-chris commented
> @fs-chris You need to make this PR into `main` and then we can backport it onto 2.x for the next 2.x release.

I cannot use `main` since it no longer works with the `RestClient` which our product heavily depends on (for working around so many other flaws in the actual client API).

Thanks anyway...

2023-11-30 16:08 UTC, dblock commented
@fs-chris I see. Make the fix in 2.x branch instead of 2.8.1

2023-11-30 16:11 UTC, dblock commented
> So, please, anyone else to do this in `main`?

Hope someone wants to pick this up. We definitely appreciate your work, and as much time as you're willing to spend on this bug!